// <auto-generated />
using System;
using Corso.Entity.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Corso.Entity.Migrations
{
    [DbContext(typeof(CorsoFormazioneContext))]
    [Migration("20240915193338_Studente")]
    partial class Studente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Corso.Entity.DAL.Aula", b =>
                {
                    b.Property<int>("Idaula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idaula"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("int");

                    b.HasKey("Idaula");

                    b.ToTable("Aula");
                });

            modelBuilder.Entity("Corso.Entity.DAL.CorsoEntity", b =>
                {
                    b.Property<int>("IDCorso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCorso"));

                    b.Property<DateOnly>("DataInizio")
                        .HasColumnType("date");

                    b.Property<string>("Durata")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IDAula")
                        .HasColumnType("int");

                    b.Property<int>("IDDocente")
                        .HasColumnType("int");

                    b.Property<string>("NomeCorso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDCorso");

                    b.HasIndex("IDAula");

                    b.HasIndex("IDDocente");

                    b.ToTable("Corso");
                });

            modelBuilder.Entity("Corso.Entity.DAL.Docente", b =>
                {
                    b.Property<int>("IDDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDocente"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDDocente");

                    b.ToTable("Docente");
                });

            modelBuilder.Entity("Corso.Entity.DAL.Studente", b =>
                {
                    b.Property<int>("IDStudente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDStudente"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDStudente");

                    b.HasIndex("Matricola")
                        .IsUnique();

                    b.ToTable("Studente");
                });

            modelBuilder.Entity("Corso.Entity.DAL.CorsoEntity", b =>
                {
                    b.HasOne("Corso.Entity.DAL.Aula", "Aula")
                        .WithMany("Corso")
                        .HasForeignKey("IDAula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corso.Entity.DAL.Docente", "Docente")
                        .WithMany("Corso")
                        .HasForeignKey("IDDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aula");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Corso.Entity.DAL.Aula", b =>
                {
                    b.Navigation("Corso");
                });

            modelBuilder.Entity("Corso.Entity.DAL.Docente", b =>
                {
                    b.Navigation("Corso");
                });
#pragma warning restore 612, 618
        }
    }
}
